name: Rhea.ai deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: '3.22.3'
          flutter-version-file: ./pubspec.yaml
      - run: flutter --version
      - run: flutter pub get
    
      - name: Install dependencies
        run: flutter pub get

      - run: flutter test

      - name: Build web
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
